Library/Controllers/AuthorsController.cs
using Library.BLL.Services;
using Library.Domain.Entities;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace Library.Controllers
{
    public class AuthorsController : ApiController
    {
        [HttpGet]
        public IHttpActionResult Autocomplete(string inputValue)
        {
            var result = new List<Author>();
            foreach (var author in new AuthorService().RequestAutocomplete(inputValue).ToList())
                result.Add(new Author() { Id = author.Id, Name = author.Name, Description = author.Description });
            return Json(result);
        }

        [HttpGet]
        public Author Create(string model)
        {
            var author = JObject.Parse(model);
            return new AuthorService().AddAuthor((string)author["Name"], (string)author["Description"]);
        }

        [HttpGet]
        public void Update(string model)
        {
            var author = JObject.Parse(model);
            new AuthorService().UpdateAuthor((int)author["Id"], (string)author["Name"], (string)author["Description"]);
        }

        [HttpGet]
        public void Delete(int id)
        {
            new AuthorService().RemoveAuthor(id);
        }

        [HttpGet]
        public IHttpActionResult Read()
        {
            var list = new AuthorService().RequestAuthorsHub();
            var result = new List<Author>();
            foreach (var author in list)
                result.Add(new Author() { Id = author.Id, Name = author.Name, Description = author.Description });
            return Json(result);
        }
    }
}

Library/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using Library.BLL.Services;
using Library.Domain.Entities;
using Library.Models;
using Newtonsoft.Json.Linq;

namespace Library.Controllers
{
    public class BookController : ApiController
    {
        [HttpGet]
        public IHttpActionResult Read()
        {
            var books = new BookService().RequestBooksHub();
            var result = new List<BookModel>();
            foreach (var book in books)
            {
                var authors = new List<string>();
                foreach (var author in book.Matches)
                    authors.Add(author.Author.Name);
                result.Add(new BookModel() { Id = book.Id, Title = book.Title, Authors = authors });
            }

            return Json(result);
        }

        [HttpGet]
        public void Update(string model)
        {
            var book = JObject.Parse(model);
            new BookService().UpdateBook((int)book["Id"], (string)book["Title"]);
        }

        [HttpGet]
        public void Delete(int id)
        {
            new BookService().RemoveBook(id);
        }
    }
}

Library/Controllers/CreateController.cs
using Library.BLL.Services;
using Library.Models;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class CreateController : Controller
    {
        public ActionResult Author()
        {
            ViewBag.Message = "Add new author.";

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Author(AuthorModel model)
        {
            ViewBag.Message = "Add new author.";
            if (ModelState.IsValid)
            {
                new AuthorService().AddAuthor(model.Name, model.Description);
            }
            return View(model);
        }
        
        public ActionResult Content()
        {
            ViewBag.Message = "Add new content.";

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Content(ContentModel model)
        {
            ViewBag.Message = "Add new content.";
            if (ModelState.IsValid)
            {
                if(model.Type == 0)
                {
                    new BookService().AddBook(model.Title, model.Content, model.Authors);
                }
                if (model.Type == 1)
                {
                    new ArticleService().AddArticle(model.Title, model.Content, model.Authors);
                }
            }
            return View(model);
        }
    }
}

Library/Controllers/GridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class GridController : Controller
    {
        // GET: Grid
        public ActionResult Author()
        {
            return View();
        }

        public ActionResult Article()
        {
            return View();
        }

        public ActionResult Book()
        {
            return View();
        }
    }
}

Library/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Http;
using Library.BLL.Services;
using Library.Models;
using System.Net;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Authors(int id = 1)
        {
            ViewBag.Message = "Authors.";
            var service = new AuthorService();
            return View(new ListingPageModel() { Authors = service.RequestAuthors(id), Page = id, PageCount = service.AuthorsCountPagination() });
        }

        public ActionResult Books(int id = 1)
        {
            ViewBag.Message = "Books.";
            var service = new BookService();
            return View(new ListingPageModel() { Content = service.RequestBooks(id), Page = id, PageCount = service.BookCountPagination() });
        }

        public ActionResult Articles(int id = 1)
        {
            ViewBag.Message = "Articles.";
            var service = new ArticleService();
            return View(new ListingPageModel() { Content = service.RequestArticles(id), Page = id, PageCount = service.ArticlesCountPagination() });
        }

        public ActionResult DBFill()
        {
            Helpers.DB.FillDB();
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

Library/Controllers/PreviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Library.BLL.Services;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class PreviewController : Controller
    {
        public ActionResult Author(int id = 0)
        {
            ViewBag.Message = "Authors.";
            return View(new AuthorService().RequestAuthor(id));
        }

        public ActionResult Book(int id = 0)
        {
            ViewBag.Message = "Books.";
            return View(new BookService().RequestBook(id));
        }

        public ActionResult Article(int id = 0)
        {
            ViewBag.Message = "Articles.";
            return View(new ArticleService().RequestArticle(id));
        }
    }
}

Library/Views/Create/Author.cshtml
@model Library.Models.AuthorModel
@{
    ViewBag.Title = "Author";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    <div class="form-horizontal">
        @using (Html.BeginForm("Author", "Create", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            if (Model != null)
            {
                <div class="alert alert-success">
                    <strong>Success!</strong> New author added to database.
                </div>
            }
            @Html.ValidationSummary(true, "", new { @class = "text-danger", @role = "alert" })
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @id = "Name" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @id = "Description" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" value="Submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        }
    </div>
</section>

Library/Views/Create/Content.cshtml
@model Library.Models.ContentModel
@{
    ViewBag.Title = "Content";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    @using (Html.BeginForm("Content", "Create", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        if (Model != null)
        {
            <div class="alert alert-success">
                <strong>Success!</strong> New content added to database.
            </div>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger", @role = "alert" })
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
            @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @id = "Title" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Content, new { @class = "col-md-2 control-label" })
            @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @id = "Content" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Type, new { @class = "col-md-2 control-label" })
            @Html.ValidationMessageFor(m => m.Type, "", new { @class = "text-danger" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Type, new List<SelectListItem>() { new SelectListItem() { Text = "Book", Value = "0" }, new SelectListItem() { Text = "Article", Value = "1" } }, new { @class = "form-control", @id = "Type" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Authors, new { @class = "col-md-2 control-label" })
            @Html.ValidationMessageFor(m => m.Authors, "", new { @class = "text-danger" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Authors, new { @class = "form-control", @id = "AuthorsAC", @name = "AuthorsAC" }) <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label"></div>
            <div class="col-md-10" id="AuthorsList">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="Submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    }

    @Scripts.Render("~/bundles/ContentUI")
</section>

Library/Views/Grid/Article.cshtml
@model Library.Domain.Entities.ContentEntity 
@{
    ViewBag.Title = "Article";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @id = "Title" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Authors", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">| 
                    @foreach (var author in Model.Matches)
            {
                            <a href="/Preview/Author/@author.Author.Id">
                                @author.Author.Name
                            </a>@Html.Raw(" | ");
                    }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Content, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @id = "Description" })
            </div>
        </div>
    </div>
</section>

Library/Views/Grid/Author.cshtml
@{
    ViewBag.Title = "Author";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    <div class="form-horizontal">
        <div id="grid" style="margin-bottom:20px"></div>
        <span id="notification"></span>
    </div>
</section>

@Scripts.Render("/bundles/AuthorGrid")

Library/Views/Grid/Book.cshtml
@{
    ViewBag.Title = "Book";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    <div class="form-horizontal">
        <div id="grid" style="margin-bottom:20px"></div>
        <span id="notification"></span>
    </div>
</section>

@Scripts.Render("/bundles/BookGrid");

Library/Views/Home/Articles.cshtml
@model Library.Models.ListingPageModel
@{
    ViewBag.Title = "Articles";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<ul>
    @foreach (var article in Model.Content)
    {
        <li><a href="/Preview/Article/@article.Id">@article.Title</a></li>
    }
</ul>
@Html.Raw(Library.Helpers.Pagination.GeneratePagination("/Home/Articles", Model.Page, Model.PageCount))

Library/Views/Home/Authors.cshtml
@model Library.Models.ListingPageModel
@{
    ViewBag.Title = "Authors";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<ul>
    @foreach (var author in Model.Authors)
    {
        <li><a href="/Preview/Author/@author.Id">@author.Name</a></li>
    }
</ul>
@Html.Raw(Library.Helpers.Pagination.GeneratePagination("/Home/Authors", Model.Page, Model.PageCount))

Library/Views/Home/Books.cshtml
@model Library.Models.ListingPageModel
@{
    ViewBag.Title = "Books";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<ul>
    @foreach (var book in Model.Content)
    {
        <li><a href="/Preview/Book/@book.Id">@book.Title</a></li>
    }
</ul>
@Html.Raw(Library.Helpers.Pagination.GeneratePagination("/Home/Books", Model.Page, Model.PageCount))

Library/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
            <input id="datepicker" />
            <script>
            $(function() {
                $("#datepicker").kendoTimePicker();
            });
            </script>
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Library/Views/Preview/Article.cshtml
@model Library.Domain.Entities.ContentEntity
@{
    ViewBag.Title = "Article";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control" style="border:none;">
                    @Html.DisplayTextFor(m => m.Title)
                </p>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Authors", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                |
                @foreach (var author in Model.Matches)
            {
                    <a href="/Preview/Author/@author.Author.Id">
                        @author.Author.Name
                    </a>@Html.Raw(" | ");
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Content, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control" style="border:none;">
                    @Html.DisplayTextFor(m => m.Content)
                </p>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        $("#grid").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: "/api/"
                },
                schema: {
                    model: {
                        fields: {
                            OrderID: { type: "number" },
                            Freight: { type: "number" },
                            ShipName: { type: "string" },
                            OrderDate: { type: "date" },
                            ShipCity: { type: "string" }
                        }
                    }
                },
                pageSize: 20,
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            height: 550,
            filterable: true,
            sortable: true,
            pageable: true,
            columns: [{
                field: "OrderID",
                filterable: false
            },
                "Freight",
                {
                    field: "OrderDate",
                    title: "Order Date",
                    format: "{0:MM/dd/yyyy}"
                }, {
                    field: "ShipName",
                    title: "Ship Name"
                }, {
                    field: "ShipCity",
                    title: "Ship City"
                }
            ]
        });
    });
</script>

Library/Views/Preview/Author.cshtml
@model Library.Domain.Entities.Author
@{
    ViewBag.Title = "Author";
}

<h2>@ViewBag.Message</h2>


<section id="createForm">
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control" style="border:none;">
                    @Html.DisplayTextFor(m => m.Name)
                </p>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <p class="form-control" style="border:none;">
                    @Html.DisplayTextFor(m => m.Description)
                </p>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Books", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <ul>
                    @foreach (var book in Model.Matches.Where(x => x.Content is Library.Domain.Entities.Book))
            {
                        <li>
                            <a href="/Preview/Book/@book.Content.Id">
                                @book.Content.Title
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Articles", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <ul>
                    @foreach (var article in Model.Matches.Where(x => x.Content is Library.Domain.Entities.Article))
                    {
                        <li>
                            <a href="/Preview/Article/@article.Content.Id">
                                @article.Content.Title
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</section>

Library/Views/Preview/Book.cshtml
@model Library.Domain.Entities.ContentEntity
@{
    ViewBag.Title = "Book";
}

<h2>@ViewBag.Message</h2>

<section id="createForm">

    <div class="jumbotron">
        <h1>@Html.DisplayTextFor(m => m.Title)</h1>
        <p class="lead">| 
            @foreach (var author in Model.Matches)
            {
                <a href="/Preview/Author/@author.Author.Id">
                    @author.Author.Name
                </a>@Html.Raw(" | ");
            }
        </p>
        <hr style="border-top: 1px solid #000;" />
        <p>@Html.DisplayTextFor(m => m.Content)</p>
    </div>
</section>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" charset="UTF-8" src="~/Scripts/References/kendo.all.min.js"></script>
    <link href="~/Content/kendo.common.min.css" rel="stylesheet">
    <link href="~/Content/kendo.default.min.css" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Browse
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Authors", "Authors", "Home")</li>
                            <li>@Html.ActionLink("Books", "Books", "Home")</li>
                            <li>@Html.ActionLink("Articles", "Articles", "Home")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Create
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Author", "Author", "Create")</li>
                            <li>@Html.ActionLink("Content", "Content", "Create")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Grid
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Author", "Author", "Grid")</li>
                            <li>@Html.ActionLink("Book", "Book", "Grid")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>